### ISSUE TITLE
fix color pannel !!

### ISSUE THREAD

**Issue by rimanshupatel** [TheNewC0der-24/Portfolio#18]
Hii,
bhavya khurana I just checking your portfolio. which is so much good with great color combination and amazing. Your github account is also cool.
Here, I want to tell you that i think i found a bug in your portfolio. **when is click on the color it can't reflected on your site.**.
I think you should to fix it soon !!  I hope you reply me shortly.
thank you :) 
![bug](https://github.com/TheNewC0der-24/Portfolio/assets/111566534/39952edd-4548-48d5-8087-cb575ba526b1)

**Comment by TheNewC0der-24** [comment]
Thank you so much for taking the time to check out my portfolio and for your kind words! I'm glad you liked the design and the color combination. I really appreciate your feedback. But basically the issue you are telling me is not actually an issue. I just put these boxes for design purpose. But now I can think to make this design thing functional. 

I'll definitely look into fixing that issue as soon as possible to ensure a better user experience for visitors like yourself.

If you have any further suggestions or feedback, please feel free to share. Your input is valuable to me.

Thanks again for reaching out!
